### ISSUE TITLE
Usar GitHub, Bitbucket ou Dreamhost?

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#1]
Cada servidor tem suas vantagens e desvantagens. Precisamos escolher qual vamos usar. 

Ver opções no [wiki](https://github.com/whysasse/mcqb/wiki/Escolhendo).

**Comment by whysasse** [comment]
Tenho mais simpatia pelo GitHub. Acho mais “mac" e gosto do mascote (#soufutil).

**Comment by enniodanieli** [comment]
Eu voto pelo GitHub
