### ISSUE TITLE
Documentar conversa do dia 2015-08-21 no wiki e criar issues

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#10]
## mcqb
- estamos de acordo sobre a estrutura de arquivos para o código
- [ ] [ISSUE] coloca esquema de estrutura do código no wiki
- [ ] [ISSUE] documenta nomenclatura de arquivos e pastas
## mcqb.wiki
- ter menos páginas. juntar informação semelhante, enquanto isso for gerenciável. cria página nova só quando precisar. 
- [ ] [ISSUE] junta todas as idéias numa mesma página
- [ ] [ISSUE] reorganiza arquivos do wiki
- [ ] [ISSUE] renomeia arquivo Índice, corrige link na home do wiki
## Issues
- milestones: setup inicial; livro; mcqb; projeto-paralelo01; ...
- labels: bug, question, etc. 
- colocamos o capítulo do livro no título da issue
- uma boa explicação de issues, milestones e labels: https://guides.github.com/features/issues/
- [ ] [ISSUE] inclui explicação de como vamos usar as issues no wiki
## A ser discutido
- [ ] [ISSUE] GitHub Pages: o site do nosso projeto, pra mostrar pros outros. Estudei como funciona e te explico pessoalmente. 
- [ ] [ISSUE] Assets: tem a ver com o site e com o código. Precisamos conversar pessoalmente.

**Comment by enniodanieli** [comment]
Eu fiz uma página chamada "Diretrizes".
Link: https://github.com/whysasse/mcqb/wiki/Diretrizes

Documentei as coisas de que falamos. Seria legal você dar uma olhada prestando atenção em detalhes porque eu tive que mexer em algumas coisas.
Se tiver alguma coisa errada, por favor, não hesite em me falar.

**Comment by enniodanieli** [comment]
Fiz tudo, só ficaram os itens de "A ser discutido".
Pelo que eu entendo, o que fala de gitHub pages, nós já temos uma issue aberta.
Abrimos uma de "assets" também?

Depois que você olhar o Wiki, você fecha esta issue?
Se for fechar, não podemos esquecer de colocar a issue de assets em algum canto.

**Comment by whysasse** [comment]
Gostei das diretrizes. 

Prefiro o nome "ecosystem" (que você escolheu) à "environment".

Eu não tinha me lidado da diferença entre exemplo e exercício, achei ótimo você incluir.
