### ISSUE TITLE
O que fazer da home do Wiki

### ISSUE THREAD

**Issue by enniodanieli** [whysasse/mcqb#12]
Já que estamos revendo a forma como organizamos o Wiki, talvez seria legal também ver o que vamos colocar na home do Wiki.
E posteriormente corrigir os links

**Comment by whysasse** [comment]
Concordo. A home está evoluindo de forma orgânica, mas seria bacana dar uma estruturadinha. 

Sugiro, por exemplo, indicar em qual parte do livro estamos.

**Comment by whysasse** [comment]
Resolvido de acordo com #14.
