### ISSUE TITLE
Documentar as decisões da conversa do dia 24/08/2015

### ISSUE THREAD

**Issue by enniodanieli** [whysasse/mcqb#14]
• Usar o template Hyde (https://github.com/poole/hyde)
• Adicionar o processing.js (http://processingjs.org)
• Documentar no wiki decisões (vamos usar GitPages, vamos usar o template Hyde, vamos usar o template cru agora e vamos melhorar depois, não vamos usar thumbnail agora)
• Documentar no wiki como criar um novo post (qual o padrão pro nome, como incluir um sketch, lugar onde colocar o sketch, futuramente o estilo do thumbnail)
• Configurar o Jekyll localmente
• Documenta usa do assets (Adobe)

**Comment by whysasse** [comment]
Criei as issues para cada item acima.
