### ISSUE TITLE
Wiki: Documentar como criar um novo post

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#20]
Documentar no wiki como criar um novo post
- qual o padrão pro nome
- como incluir um sketch
- lugar onde colocar o sketch
- futuramente o estilo do thumbnail

**Comment by enniodanieli** [comment]
Eu não sei ainda. Talvez precisemos conversar.
Só queria atualizar a lista com uma questão que surgiu na nossa conversa do cartório: 
- qual o padrão pro nome
- como incluir um sketch
- lugar onde colocar o sketch
- futuramente o estilo do thumbnail
- categoria

**Comment by whysasse** [comment]
Comentamos também de talvez incluirmos o nome/bio do autor do post. 

Sugiro dividirmos as features em duas listas. Veja abaixo. 

Para o lançamento:
- definir o padrão pro nome do post
- documentar como incluir um sketch no post
- criar um lugar (diretório) onde colocar os sketches
- ter comentários no fim do post

Futuramente:
- ter um thumbnail por post
- ter categorias
- incluir bio do autor no fim do post

**Comment by enniodanieli** [comment]
Digamos que temos os seguintes motivos pros posts:
- Exercício
- Variação de exercício
- Exemplo
- Variação de exemplo
- Projeto Ecosystem
- Projeto Paralelo

Então sugiro abaixo.

### Exercício, Exemplo e variações

Normal
[#capítulo]+[tipo]+[#id]

E para variações
[#capítulo]+[tipo]+[#id]+"var_"[#idVar]

**capítulo** = o número do capítulo do livro
**tipo** = example ou exercise
**id** = o número do exercício
**idVar** = o número da variação (talvez uma letra?)

### Ecosystem Project

"Ecosystem"+[#id]
**id** = o número do exercício que corresponde ao capítulo do livro

### Projeto Paralelo

Eu imagino projetos paralelos tenham um nível de complexidade um pouco mais que variações. Então não vejo muito sentido relacionar um projeto paralelo a um capítulo específico. Se houver necessidade, podemos citar os conceitos principais no corpo do texto, mas sem muita esquematização.

"ProjetoParalelo"+[#id]
**id** = seqüência numérica que deve começar em 01

O que você acha? Muito simples?

Não toquei nos assuntos futuros:
- ter um thumbnail por post
- ter categorias
- incluir bio do autor no fim do post

**Comment by whysasse** [comment]
Concordo com suas sugestões, bem mais claro do que eu tinha pensado.

Aqui vão comentários e sugestões:
- O nome do arquivo deve começar com a data, é uma exigência do Jekyll.
- Sugiro usar underline entre os elementos, pra facilitar a leitura.
- Além disso, já que é um projeto artístico e divertido antes de tudo, sugiro ter um subtítulo opcional.

Vou dar um exemplo com as sugestões, daí vamos ver se entendi sua nomenclatura e então o que você acha do resultado.

**Nome do arquivo:**
- 2015-09-01-chp01-example01-var01-Fireflies-in-the-sky.md

**Título do post:**
- chp01_example01_var01 (Fireflies in the sky)

O que acha?

**Comment by whysasse** [comment]
Além disso, gostei da divisão que você fez: 
- Exercises, examples and variations
- Ecosystem Project
- Parallel Projects

Essas já podem ser categorias do site/blog, não acha?

Eu incluiria também as seguintes categorias:
- referências de creative coding que quisermos compartilhar (outros projetos, libraries, sites, etc.), que serve até de bookmark pra gente.  
- posts pessoais, sempre é bom poder desabafar...

**Comment by enniodanieli** [comment]
O título do post é como os usuários finais vão ver?
Se for isso, eu pessoalmente não gostei. Mas entendo a necessidade de se parecer com o nome do arquivo pra facilitar nossa vida.
Por curiosidade, tem que ser underscore? Se for hífen, fica tudo igual de uma vez.
O título é opcional mesmo? Ou seja, se não tiver, não vai quebrar?

Concordo na parte das categorias. Já posso dar isso como definido.
Você tem ideia de como programa isso? Vou abrir uma issue genérica pra adicionar categorias e quando decidirmos isso, a gente refina a issue.

Sobre as referências, isso não era trabalho do Wiki?
Não tenho problema de ter referência no blog, mas daí matamos as do Wiki.

Posts pessoais é ok.
Neste momento não me vejo escrevendo sobre o assunto, mas vai que dá um ânimo, né? E se você quiser, claro, fique a vontade.

**Comment by whysasse** [comment]
Sugestão pro nome dos posts: 

**Nome do arquivo:**
- 2015-09-01-chp01-example01-var01-Fireflies-in-the-sky.md

**Título do post (obrigatório):**
- Chp01 | Example 1 | Var 01 || Fireflies in the sky

**Tags do post:**
- chapter01
- example
- variation

Sobre as referências: 
- ficam no wiki
- se a gente fizer uma variação de uma referência, coloca link no post e no wiki
