### ISSUE TITLE
Configurar o Jekyll localmente

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#21]
Ver https://help.github.com/articles/using-jekyll-with-pages/

**Comment by whysasse** [comment]
Já fiz, depois vou documentar e te acompanho na instalação e configuração.

**Comment by enniodanieli** [comment]
Fá, eu sei que esta issue já foi fechada, mas eu tentei instalar e deu um erro. Vou precisar da sua ajuda sim, por favor.

**Comment by whysasse** [comment]
Na verdade eu nem sei pq eu fechei. Reabrindo...

**Comment by whysasse** [comment]
Resolvi! 
- Roda `git --version` no terminal. 
- Vai pedir pra atualizar Command Line Tools ou algo do Xcode. Aceita e atualiza. 
- Fecha o terminal, abre de novo e roda `git --version` de novo. 
- Se rodar sem erro, dá pra continuar a instalação do Jekyll (isto é, entra no diretório do MCQB, entra no branch `gh-pages`, roda `bundle install` e continua dali).
