### ISSUE TITLE
Traduzir wiki pro inglês

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#27]
De acordo com conversa de ontem, 2015-08-25.

**Comment by whysasse** [comment]
Acho bom ter uma issue por página, assim um sabe no que o outro está trabalhando. Que tal, @enniofranco ?

**Comment by enniodanieli** [comment]
Eu gostei da ideia.
Já tinha visto seu post mas não consegui responder ainda. Desculpe.
