### ISSUE TITLE
Wiki: Documentar configuração do ambiente do Processing

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#31]
- Versão do Processing que usamos
- Libraries e tools que formos instalando
- IDE (a própria que vem com o Processing, não o Eclipse ou outra - pelo menos por enquanto)

**Comment by enniodanieli** [comment]
As libraries ficaram pra quando instalarmos.
Mas coloquei lá no diretrizes de forma simples. Você acha que precisa escrever melhor?

**Comment by whysasse** [comment]
Está ótimo!
