### ISSUE TITLE
quais sao as diretrizes artisticas para o projeto?

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#33]
ja escrevemos as diretrizes técnicas do projeto, ne? 

bom, recomecei um curso de creative coding para dar uma lembrada no processing e vi que eles na verdade dao uma visao mais ampla de arte criada por codigo. 

dai eu me peguei perguntando: o que nos move a fazer arte com codigo? 

para pensar, expandir e discutir.

**Comment by enniodanieli** [comment]
Essa é uma questão bem grande pra mim.
Talvez seja melhor marcarmos uma conversa por skype?

**Comment by whysasse** [comment]
Resolvemos reservar um momento em cada encontro para discutir a questão artística. 

É um projeto artístico? Sim, acreditamos que sim. 

Não existe um objetivo pré-definido. Existe uma vontade. 
O.s objetivo.s se define.m à medida que o projeto avança. 

O projeto se baseia numa vontade de explorar as possibilidades da arte generativa. Para aumentar nosso potencial, vamos nos equipar com as ferramentas que esperamos encontrar no livro Nature of Code. 

O curso [Creative Coding](https://www.futurelearn.com/courses/creative-coding/2/todo/2378) ajuda com essas questões.

Melhor ir mais devagar e a fundo nos exercícios, mesmo que pareçam bobos.
