### ISSUE TITLE
Como gerar o html do sketch pra por online?

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#4]
Se for gerar html, acho interessante gerar um html por versão do sketch pra ter histórico.

E se formos por este caminho, podemos incluir no wiki uma seção de "regras do projeto".

**Comment by whysasse** [comment]
A pergunta se desdobra, na verdade, sobre a organização de pastas e arquivos pro projeto. 

Além disso, podemos ter uma página para cada exercício/exemplo/variação, cada um com o código-fonte e o sketch rodando.

**Comment by enniodanieli** [comment]
Acho que já conversamos sobre pastas.
Eu sugeri de fazermos pastas por capítulos e dentro dessas pastas tem as pastas de cada exercício. Foi isso que combinamos no final? Não lembro. Acho que seria legal colocar isso no Wiki depois de definirmos.

Mas sobre a página e o HTML, eu lembro de não termos feito nenhuma definição. Vamos falar pessoalmente ou por Skype pra resolver isso? Acho que é uma conversa um pouco mais complexa do que por mensagens, o que você me diz?

**Comment by whysasse** [comment]
isso, vamos falar pessoalmente. eu não anotei o que a gente tinha decidido. da próxima vez, a gente vai anotando. #ficadica. 

sobre a organização, acho que sua sugestão de organização de pastas é boa. 

será que tem a ver com o que falamos ontem do índice dos exercícios do livro e de como vamos "enriquecendo" com nossas variações? ou será que é outra coisa? 

o que é wiki, o que é código e o que é pages? sugiro que a gente desenhe uns esquemas, pois estou me perdendo.

**Comment by whysasse** [comment]
Tá resolvido. Ver issue #10.
