### ISSUE TITLE
Considerar o uso de two-factor-authentication

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#6]
Segurança!!! 

Veja: https://help.github.com/articles/about-two-factor-authentication/

**Comment by enniodanieli** [comment]
Se eu entendi bem, isso é pra nossas contas individuais.
Ou seja, é uma sugestão pra eu aumentar a segurança da minha conta e pra você aumentar a segurança da sua?

**Comment by whysasse** [comment]
isso mesmo. cada um configura se quiser. mas se um não quiser, não adianta o outro fazer pq vai ter brecha de um lado. e aí, topas?

**Comment by enniodanieli** [comment]
Fa, eu olhei a configuração e uma coisa me deixou encucado: não funciona por SMS no Brasil.
Se eu fizer por aplicativo e perder o telefone, eu literalmente perco a conta. Eu realmente não queria ter que anotar código em papel pra caso eu perca o telefone ou apague o aplicativo sem querer.
Você se incomoda se eu não fizer? Se você fizer, pelo menos um lado fica um pouco mais forte.

**Comment by whysasse** [comment]
São bons argumentos, eu não tinha considerado tudo isso. 

Melhor deixar pra lá.
