### ISSUE TITLE
Considerar o GitPages para o site do projeto

### ISSUE THREAD

**Issue by whysasse** [whysasse/mcqb#7]
Acho prático, fica tudo dentro do GitHub mesmo. 

Veja: https://pages.github.com

**Comment by enniodanieli** [comment]
Fa, eu gostei porque eu entendi que é tudo automático. Mas eu não consigo entender o todo ainda :-(
Talvez eu precise entender melhor o gitHub como um todo?

**Comment by whysasse** [comment]
sim e não. falamos pessoalmente quando formos falar sobre wiki, código e pages.

**Comment by whysasse** [comment]
Agora que conversamos sobre a estrutura do código, do wiki e das issues, vai ficar mais fácil resolver isso. Eu incluí na issue #10.
